### ISSUE TITLE
Speichern von Contents/Images über OutputStram

### ISSUE THREAD

**Issue by yveskaufmann** [yveskaufmann/SharkNetJavaFX#15]
Das Speichern von Contents über InputStream, wie ist das gedacht ? 

Habe Probleme damit Bilder zu speichern, die ich nicht in Daten vorliegen. 
Ich muss bisher, dass Bild über einen ByteOutputStream in ein Byte-Array umwandeln um der Content Klasse ein ByteStream zu übergeben. So werden die Daten praktisch mehrfach eingelesen.

Ich denke es wäre besser, dass das Content Interface sowohl einen OutputStream für das schreiben als auch einen InputStream für das lesen anbietet. Ähnlich wie es das Information 
[ Information Interface] (https://github.com/SharedKnowledge/SharkFW/blob/master/src/main/java/net/sharkfw/knowledgeBase/Information.java) im Shark Framework tut: 

````Java
public interface Content {
        ...
	/**
	 *Returns the content as IO Stream
	 */
	public InputStream openInputStream();

        /**
	 * Enables you to priovide data to the content.
	 */
	public OutputStream openOutputStream();
       ...
}
````
So können die unterschiedlichsten Arten von Contents Implementiert werden z.b

- ByteArrayContent erstellt über sharkNet.getContentFactory().create(byte[])
- StringContent erstellt über sharkNet.getContentFactory().create(String)

**Comment by lingofant** [comment]
It*s new and very important that the Content has to need a owner which is the current user

**Constructors:**
public ImplContent (String message, Profile owner);
public ImplContent(InMemoInformation file, Profile owner);
public ImplContent(Profile owner);

**Add Files:**
The Methods return true if the file is smaller than the maxfilesize in settings, else it returns false and the file gets not saved
public boolean setFile(File f);
public boolean setInputstream(InputStream is)

**Get Files:**
public OutputStream getOutputstream();
public InputStream getInputstream();

**File Properties:**
public String getMimeType();
public void setMimeType(String mimeType);

public String getMessage();
public void setMessage(String message);

public String getFileName();
public void setFilename(String filename);

**More Functions are possible if working with a InMemoInformationFile of the Shark Framework:**
public InMemoInformation getInformationFile();
public void setInformationFile(InMemoInformation file);


**Reminder and Voting**
public ImplVoting addVoting(String question, boolean singleqoice);
public ImplVoting getVoting();
public Reminder getReminder();
public void setReminder(Reminder reminder);

**Comment by lingofant** [comment]
All other Constructors are still available but annotated as Deprecated.
