### ISSUE TITLE
Content Mimetypes

### ISSUE THREAD

**Issue by yveskaufmann** [yveskaufmann/SharkNetJavaFX#16]
Wir sollten besser den MimeType des Contents speicher anstatt der Extension. 
Files-Extension sind nicht standardisiert, Mime-Types hingegen schon und zu dem
speichern wir die Files-Extensio bereits über den Dateinamen.

**Comment by lingofant** [comment]
Mimetypes müssen über setMimeType gesetzt werden.
Keine Validierung ob dieser gültig ist
