### ISSUE TITLE
Setting Dummy

### ISSUE THREAD

**Issue by johann44** [yveskaufmann/SharkNetJavaFX#18]
Ich bräuchte ne klasse ImplSetting o.ä. mit dummydaten wie zb

- radar ist an oder aus
- wifidirect ausschalten nach .. min
- Weiterleiten bis zu .. MB
- smtp server
- imap server

**Comment by lingofant** [comment]
wie sollen die default-daten sein.
Also wenn ein neues Profil angelegt werden

**Comment by lingofant** [comment]
Soll die Filesize von der GUI überprüft werden oder von der API?

**Comment by johann44** [comment]
Mein Vorschlag für die Default-Daten:
- Radar aus
- Wifidirect timer auf 10 min
- Weiterleiten bis 10 mb
- smtp, imap, mailpasswort auf leer lassen

- sync: alles an (chats, kontakte, ...)
- sync: Synchronisationsmethode Mail ausgewählt

**Comment by lingofant** [comment]
radarON = false;
		nfc = false;
		bluetooth = false;
		tcp = false;
		wifi = true;
		mail = false;

		syncProfile = true;
		syncConctact = true;
		syncChat = true;
		syncTimeline = true;
		syncHausaufgaben = true;

		syncnfc = false;
		syncbluetooth = false;
		synctcp = false;
		syncwifi = false;
		syncmail = true;

		wifiON = 10;
		maxFileSize = 10;
