### ISSUE TITLE
message sorting

### ISSUE THREAD

**Issue by BenjaminReenK** [yveskaufmann/SharkNetJavaFX#19]
Please add some parameter, so we can choose newest or oldest messages first

**Comment by lingofant** [comment]
bei den gettern für Listen die Timestamps enthalten gibt es jetzt den boolean descent
wenn ihr ihn auf true setzt ist die sortierung wie jetzt auch, auf false genau umgedreht
(vorsicht bei den Dummy-Daten gibt es identische timestamps da diese automatisch angelegt werden, kann sein das sich bei der umsortierung nicht wirklich viel passiert)
