### ISSUE TITLE
SharkNet.login()

### ISSUE THREAD

**Issue by BenjaminReenK** [yveskaufmann/SharkNetJavaFX#2]
need some login function for Loginscreen

public boolean login(Profile p, String password) or sth like that

**Comment by lingofant** [comment]
in der Klasse des Profils gibt es jetzt die Methoden "public void setPassword(String password)" und "public boolean login(String password)".
Profile p;
boolean loggedIn = p.login("mypassword");
VORSICHT: Passwort wird als leerer String initialisiert ("") -> wenn kein Passwort gesetzt ist liefert das true zurück
