### ISSUE TITLE
Getter für einzelne einträge der blacklist

### ISSUE THREAD

**Issue by johann44** [yveskaufmann/SharkNetJavaFX#20]
ich bräuchte ne methode 

getBlacklist().**get(index)**

oder so ähnlich um einzelne Contacts aus der Blacklist zu holen

**Comment by BenjaminReenK** [comment]
blacklist.getList() liefert doch eine Liste zurück. Und Listen haben bereits eine .get(index) Methode. Oder was meinst du?

**Comment by johann44** [comment]
stimmt, hatte das getList() vergessen.
