### ISSUE TITLE
Settings: was soll synchronisiert werden

### ISSUE THREAD

**Issue by johann44** [yveskaufmann/SharkNetJavaFX#24]
Ich bräuchte Boolean-Variablen jeweils ob synchronisiert werden soll:
- Profil
- Kontakte
- Chats
- Timeline
- Hausaufgaben

**Comment by lingofant** [comment]
boolean syncProfile, syncConctact, syncChat, syncTimeline, syncHausaufgaben;
Getter and Setter
issyncProfile();
setsyncProfile();
