### ISSUE TITLE
Profil: Setter für eigene Mail-Adresse

### ISSUE THREAD

**Issue by johann44** [yveskaufmann/SharkNetJavaFX#26]

**Comment by lingofant** [comment]
Die eigene E-Mail wird über den Contact festgelegt.... reicht das nicht aus?

**Comment by johann44** [comment]
wenn man die sync per mail nur über die im Contact hinterlegte mailadresse abwickeln darf, schon

**Comment by lingofant** [comment]
hab das bei settings untergebracht, macht für die sync mehr sinn
