### ISSUE TITLE
Listener / Event for new chat message

### ISSUE THREAD

**Issue by BenjaminReenK** [yveskaufmann/SharkNetJavaFX#3]
need a listener / event in implchat for new chat messages

**Comment by lingofant** [comment]
/**
 * This Interface have to be implemented to receive Notifications when sth is received
 */
public interface GetEvents {
	public void receivedMessage(Message m);
	public void receivedFeed(Feed f);
	public void receivedComment(Comment c);
}

SharkNet-Class:

/**
	 * Adds Listener to the List of Listener
 	 * @param p
	 * @param listener
     */
	public void addListener(Profile p, GetEvents listener);

	/**
	 * Methods calls all Methods of registered listeners when the profile matches a contact in the recipientslist of the message
	 * @param m
     */
	public void informMessage(Message m);

	/**
	 * Methods calls all Methods of registered listeners and informs about feed
	 * @param f
     */
	public void informFeed(Feed f);

	/**
	 * Methods calls all Methods of registered listeners and informs about comment
	 * @param c
     */
	public void informComment(Comment c);


Usage:

public class TestListener  implements GetEvents{
	@Override
	public void receivedMessage(Message m) {
		System.out.println(m.getContent().getMessage());
	}

	@Override
	public void receivedFeed(Feed f) {
		System.out.println(f.getContent().getMessage());
	}

	@Override
	public void receivedComment(Comment c) {
		System.out.println(c.getContent().getMessage());
	}
}
