### ISSUE TITLE
Titel und Bild von einem GruppenChat 

### ISSUE THREAD

**Issue by viktorowich** [yveskaufmann/SharkNetJavaFX#4]
Ich brauche eine Funktion getTitle(),getImage von einem Chat. 
Bei einer einzelnen Person soll der Name der Person zurückgegeben werden und 
bei einem GruppenChat soll der Titel ausgegeben werden. 
Wenn ich alle Chats in einer ListView anzeige, müssen da auch Titel und Bild hin.

**Comment by lingofant** [comment]
Gruppenchats habe ich noch nicht implementiert.
Wie hättest du denn gerne die Rückgabe aller Chats? 
Ich würde vorschlagen: Eine Liste mit allen Chats (also Gruppen- und Einzelchats). Die Methode getContact würde dann immer eine Liste von Contacts zurückgeben die bei Einzelchats nur ein Element enthält.

**Comment by viktorowich** [comment]
Du hast es ja schon als Liste von Chats zurück gegeben, ob Gruppen oder Einzelchat würde ich keinen Unterschied machen. 
Die haben wiederum eine Liste von Messages. 
getContact klingt gut. 
Gruppenchat hat halt immer einen Titel.

**Comment by lingofant** [comment]
Bild und Titel implementiert.
Bild wird als Content zurückgeliefert. Das Default Bild ist das Profilbild des ersten Kontakts
