### ISSUE TITLE
Settings: port-Feld für TCP-Server

### ISSUE THREAD

**Issue by johann44** [yveskaufmann/SharkNetJavaFX#54]
Ich bräuchte bitte ein Integer in der der Port für den TCP-Server gespeichert wird..

**Comment by lingofant** [comment]
Schwotzer meinte wir packen die Adresse komplett in einen String und das wäre ok

**Comment by johann44** [comment]
ok und wie heißt der string? steh grad aufm schlauch..

**Comment by yveskaufmann** [comment]
Ich denke du sollst einen String aufbauen der Host-Adresse und den Port enhält.
```
Host-Adresse:Port
```
Im [rfc3986](https://tools.ietf.org/html/rfc3986#section-3) ist das Format ausführlicher beschrieben.
