### ISSUE TITLE
Adding getter and setter for Configuration objects into SharkNet interface

### ISSUE THREAD

**Issue by blackicetee** [yveskaufmann/SharkNetJavaFX#58]
This is my current version of the Configuration Interface:
[Configuraiton.txt](https://github.com/yveskaufmann/SharkNetJavaFX/files/368838/Configuraiton.txt)

**Comment by lingofant** [comment]
Würde sagen das ein anderer Name sinnvoll wäre.
Zur Abgrenzung zwischen Settings und Configuration.
Leg die Klasse und das Interface bitte selbst an. Die Getter/Setter mach ich dann

**Comment by blackicetee** [comment]
Ok Done, gibt jetzt SchoolMetadata Interface ImplSchoolMetadata und DummySchoolMetadata.

**Comment by blackicetee** [comment]
Getters und Setters sind auch angelegt.
