### ISSUE TITLE
Question! SharkNet Maven Projekt import in Android Gradle?

### ISSUE THREAD

**Issue by blackicetee** [yveskaufmann/SharkNetJavaFX#60]
Hey ihr,
ich hoffe einer von euch kann meine Frage beantworten :)
Innerhalb miener Android Anwendung will ich meine Daten im SharkNet speichern.
SharkNet widerum wird mit Maven gebuildet richtig!?
Meine Android Anwendung wird mit Grandle gebuildet
und IntelijIdea unterstützt nicht die Verwendung von Gradle Projekten und nicht Gradle Projekten. 
Wie kann ich dann gegen eure SharkNet API programmieren ?

Lieben Gruß Thilo :dancer:

**Comment by yveskaufmann** [comment]
Hi, 

die einfachste Möglichkeit ist die SharkNet-API als Dependency einzubinden. 
Alternative könntest du auch versuchen den Build der API in dein Gradle Script zu integrieren, was ich dir aber nicht empfehlen kann.

## Einbinden der Dependency

Aktuell ist weder das Shark-Framework noch die SharkNet-API über ein zentrales Maven Repository 
veröffentlicht wurden. Daher ist es erforderlich die benötigten Artifacts/Module manuell ins lokale Maven Repository zu installieren, damit diese als Dependencies in deinem Gradle Projekt aufgelöst werden können.

Dazu befolgst du folgende Schritte:

_1. Besorge dir eine Kopie des Repositories_

```
git clone https://github.com/yveskaufmann/SharkNetJavaFX
```

_2. Installiere das SharkNet-API Artifact/Modul in das lokalen Maven Repository_ 

```
cd SharkNetJavaFX
mvn install
```

Sofern mvn nicht als Befehl erkannt wird, müsstest du dir [Maven installieren](https://maven.apache.org/install.html).  

_3. Einbinden der Dependency in dein Gradle Projekt_

Dazu öffnest du deine build.gradle Datei und fügst das lokale Maven Repository 
zu der Liste der Repositories.

```
repositories {
    jcenter()
    mavenLocal()
}
```

Anschließend kannst du die SharkNet-API als Dependency hinterlegen.

Sofern es zu Versionskonflikten zwischen den von SharkNet und Android bereitstellten jars kommt,
müsstest du die entsprechenden Module ausschließen, so wie ich es exemplarisch mit dem junit Module gemacht habe.

```
dependencies {
    ...
    compile ('net.sharksystem:sharknet-api:0.1.0') {
        exclude group:'junit', module:'junit'
    }
   ...
}
```

Sofern du  Änderungen an der SharkNet-API in der Kopie des Repositories vorgenommen hast 
müsstest du Schritt 2 wiederholen und im IntelliJ/AndroidStudio über den Gradle Reiter das
Project refreshen.

Anschließend solltest du gegen unsere API Programmieren können.

**Comment by blackicetee** [comment]
Super detaillierte Antwort, danke dafür :)
