### ISSUE TITLE
Chat ID 

### ISSUE THREAD

**Issue by viktorowich** [yveskaufmann/SharkNetJavaFX#7]
ich brauche eine getChatID() Funktion 
da die Chats ständig in einer anderen Reihenfolge angezeigt werden (Sortierung nach Zeit), brauche ich eine ID, damit ich es 1:1 zuordnen kann

**Comment by lingofant** [comment]
Es wird ein Random Integer als ID erzeugt und in der DB abgeglichen das diese noch nicht vergeben ist. 
In Shark wird später implementiert, das die ID im Chat gespeichert wird.

**Comment by viktorowich** [comment]
vielleicht verstehen wir uns falsch 
aber wenn es dann implementiert ist im Shark, brauche ich doch trotzdem eine 
Möglichkeit über die API zugreifen zu können. 

Ich brauche ja keinen Setter sondern einen Getter

**Comment by lingofant** [comment]
Nein, kleines Missverständnis.
Die IDs werden bereits vergeben. Allerdings wird jedes Mal wenn das Chat-Object erzeugt wird eine neue ID vergeben. In Shark muss nur noch implementiert werden das das Persistent gemacht wird.
Danke das passt, oder?

**Comment by lingofant** [comment]
besprochen, erledigt
